### ISSUE TITLE
Complete Client

### ISSUE THREAD

**Issue by hacdias** [ipfs/js-kubo-rpc-client#129]
This is a tracking issue for completing the JS Kubo RPC client. Right now, the client is decoupled from the old `ipfs-http-api`. However, there are still tasks to be done. For more context, read [this](https://www.notion.so/pl-strflt/Generating-Kubo-RPC-Clients-Or-Not-da5a598ec16645d99ed2eb3a8ac6c744). Following steps:

- [ ] Rewrite in TypeScript (#128)
- [ ] Generate useful documentation (#113)
- [ ] Fix remaining issues noticed during migration (#56), and go over the issues page
- [ ] Update README to clarify that the repository has documentation and should be used instead of the old HTTP Client.
- [ ] Add ingratiation to Kubo's CLI to ensure that all commands are present in the JS Kubo Client once new PRs are open (#47). We can add a ignore list for some commands, such as `config/show` that have no effect remotely.
- [ ] Swap client in our apps to smoke-test it and fix papercuts
    1. ipfs-companion
    2. ipfs-desktop
        1. ipfsd-ctl
- [ ] Sync with the Docs team, allowing them to update docs.ipfs.tech, guides, courses (including [https://proto.school/course/ipfs](https://proto.school/course/ipfs)), and examples (https://github.com/ipfs-examples/js-ipfs-examples)  to mention/use `js-kubo-rpc-client` instead of `ipfs-http-client` when the backend is Kubo.
